### PR TITLE
Started incorporating required libraries from SDK Demo App

### PR DESCRIPTION
**Pull request by jahway603**
Added buildSrc/Dependencies.kt resulting in easier readable build.gradles. Incorporated required libraries from SDK Demo App.

### CODE REVIEW

**Comment by leto** [comment]
@jahway603 this looks awesome!! Can you please send this PR to the `dev` branch (that is a good default for all new PRs in all repos) and also, can we make it use our fork of the bip39 lib? https://github.com/MyHush/kotlin-bip39

**Comment by leto** [comment]
@DenioD @jahway603 we should chat about the best way forward for this code

**Comment by leto** [comment]
@jahway603 this looks like good progress. How can I help pass the scan data correctly? Do you have any ideas of what is failing?

**Comment by leto** [comment]
@jahway603 this conflicts and i think maybe can be closed, since your new PR replaced it

**Comment by jahway603** [comment]
closed and replaced by #106

**Pull request closed without merging**
