### PR TITLE
Add 'About' page

### PR DESCRIPTION
**Pull request by gilardh**
- Add 'About' page
- Add Copyright in 'About' page
- Add License GNU in 'About' page

Screenshot_20191120-230959_SilentDragon
Screenshot_20191120-230514_SilentDragon
Screenshot_20191120-231931_SilentDragon

### CODE REVIEW

**Comment by leto** [comment]
@gilardh it seems that we are missing one of the versions, there should be a version of SD/SDL and the version of SDA rendered.

Extra bonus if you can show the difference from pairing with SD + SDL (that isn't shown currently)

**Comment by gilardh** [comment]
@leto Right, the text of 'SilentDragon' is incomplete on 'About' page. I will change to 'SilentDragonAndroid'

**Comment by leto** [comment]
@gilardh to clarify, we should see 2 versions: The "peer" (which will be SD or SDL) and the local version of SDA. Currently our app does not differentiate between the peer being SD or SDL, it only gives a version number. Since SD + SDL use offset version numbers that don't yet overlap, it's possible to tell which peer you are connected to, but this is not great.

**Comment by gilardh** [comment]
@leto I added a text correction in this PR.
I replace 'SilentDragon' to 'SilentDragonAndroid'

Screenshot_20191121-214153_SilentDragon

**Comment by gilardh** [comment]
Addition of the distinction between SD or SDL will be made in another PR than this one.

**Pull request merged**
